# .circleci/config.yml for CircleCI 2.0
version: 2
jobs:
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: ./gradlew test


workflows:
  version: 2
  build:
    jobs:
      - test
