# .circleci/config.yml for CircleCI 2.0
version: 2
jobs:
  java8:
    docker:
      - image: java:openjdk-8u111-jdk-alpine
    working_directory: ~/repo
    steps:
      - run: ls
      - run: pwd
      - run: ./gradlew test

workflows:
  version: 2
  build:
    jobs:
      - java8
